// Riverpod providers for business data.
// Used by OnboardingScreen, AppShell, and any screen that needs
// the active business details.

import 'package:riverpod_annotation/riverpod_annotation.dart'; // @riverpod annotation
import '../../../core/di/repository_providers.dart'; // businessRepositoryProvider
import '../../../features/auth/application/auth_providers.dart'; // currentSupabaseUserProvider, activeBusinessIdProvider
import '../../../shared/models/business.dart'; // Business Freezed model
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'business_providers.g.dart'; // generated by build_runner

// userBusinessListProvider: loads all businesses the logged-in user belongs to
// Returns List<Business> from business_members join in BusinessRepository
// Used by OnboardingScreen to get the business created during signup
@riverpod
Future<List<Business>> userBusinessList(UserBusinessListRef ref) async {
  // Watch the Supabase auth user - rebuilds if user changes
  final user = ref.watch(currentSupabaseUserProvider);
  // Return empty list if no user logged in (guard against null)
  if (user == null) return [];
  // getUserBusinesses queries business_members WHERE uid = user.id
  return ref.read(businessRepositoryProvider).getUserBusinesses(user.id);
}

// activeBusinessProvider: streams the currently selected business details
// Watches activeBusinessIdProvider - rebuilds when Admin switches business
// Used by AppShell (business name in AppBar) and throughout the app
@riverpod
Future<Business?> activeBusiness(ActiveBusinessRef ref) async {
  // Watch activeBusinessIdProvider - this is the UUID string set after login
  final id = ref.watch(activeBusinessIdProvider);
  // Return null if no business selected yet (e.g. before onboarding)
  if (id == null) return null;
  // getBusiness fetches one business row by UUID from Supabase
  return ref.read(businessRepositoryProvider).getBusiness(id);
}

// UpdateBusinessNotifier: saves changes to the business profile
// Called from OnboardingScreen and BusinessSettingsScreen (later days)
@riverpod
class UpdateBusinessNotifier extends _$UpdateBusinessNotifier {
  // Initial state: idle, no update in progress
  @override
  AsyncValue<void> build() => const AsyncValue.data(null);

  // update: sends the updated Business object to Supabase
  // Shows AsyncLoading state while saving (disables Save button in UI)
  Future<void> update(Business b) async {
    state = const AsyncValue.loading(); // triggers spinner on Save button
    // AsyncValue.guard catches any Supabase errors and wraps in AsyncError
    /* In Riverpod 2.x the mounted property exists on ConsumerState (inside Flutter widgets) but not on Ref inside a Notifier class. The pattern changed between Riverpod 1.x and 2.x:
    // final result = await AsyncValue.guard(
    //     () => ref.read(businessRepositoryProvider).updateBusiness(b));
    // // Check mounted before updating state (widget may be disposed)
    // if (ref.mounted) state = result;
 In Riverpod 2.x the mounted property exists on ConsumerState (inside Flutter widgets) but not on Ref inside a Notifier class. The pattern changed between Riverpod 1.x and 2.x:*/

    state = await AsyncValue.guard(
        () => ref.read(businessRepositoryProvider).updateBusiness(b));
  }
}
